name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: composer install
      - name: Push
        run: |
          git config --global user.email "github-action@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update composer.lock"
          git push pantheon remote
