name: Release

on:
  push:
    branches: 
     - master

permissions:
  contents: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Build
        run: pnpm build

      - name: Create Release
        id: create_release
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          publish: pnpm ci:publish
          createGithubReleases: true
          


      # - name: Upload built files to release
      #   if: steps.create_release.outputs.published == 'true'
      #   run: |
      #     RELEASE_URL=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }} | jq -r '.url')
      #     for package in packages/*; do
      #       PACKAGE_NAME=$(basename $package)
      #       BUILT_FILE_PATH=$package/dist/* # Adjust the path to your built files
      #       if [ -f "$BUILT_FILE_PATH" ]; then
      #         curl -X POST \
      #           -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
      #           -H "Content-Type: application/zip" \
      #           --data-binary @"$BUILT_FILE_PATH" \
      #           "$RELEASE_URL/assets?name=$(basename $BUILT_FILE_PATH)"
      #       fi
      #     done
