name: Release

on:
  push:
    paths:
      - 'packages/**'
      - ".changeset/**"
    branches: 
     - master

permissions:
  contents: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Bump version or create release
        id: create_release
        uses: changesets/action@v1
        with:
          version: pnpm exec changeset version
          # Using `changeset tag` we only want to create a release 
          # If we want to publish to a npm (or github) registry, use `changeset publish` instead
          publish: pnpm exec changeset tag

      - name: Package compiled plugins as zip files
        if: steps.create_release.outputs.published == 'true'
        run: pnpm build:zip

      - name: Attach plugin artifacts to it's release
        if: steps.create_release.outputs.published == 'true'
        run: ./github/scripts/upload-zip.sh
        env: 
          PUBLISHED_PACKAGES: '${{ steps.create_release.outputs.publishedPackages }}'