name: Release

on:
  push:
    paths:
      - 'packages/**'
      - ".changeset/**"
    branches: 
     - master

permissions:
  contents: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Create Version PR
        id: create_release
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          publish: pnpm ci:publish

      - name: Create plugin zip files
        if: steps.create_release.outputs.published == 'true'
        run: pnpm ci:release-build

      - name: Add artifacts to the release
        if: steps.create_release.outputs.published == 'true'
        run: |
          publishedPackages=${{ steps.create_release.outputs.publishedPackages }}
          publishedPackages=$(echo "$publishedPackages" | jq -c '.[]')

          for pkg in $publishedPackages; do
            pkgName=$(echo "$pkg" | jq -r '.name')
            pkgVersion=$(echo "$pkg" | jq -r '.version')
            tag="${pkgName}@${pkgVersion}"
            packageName=$(echo "$pkgName" | sed 's/@.*\///')
            zipFileName="${packageName}.zip"
            filePath="./packages/${packageName}/${zipFileName}"

            if [[ -f "$filePath" ]]; then
              echo "Uploading $filePath to release $tag"
              gh release upload $tag $filePath --clobber
            else
              echo "File not found: $filePath"
            fi
          done
